// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop_Project.API.Data;

#nullable disable

namespace Webshop_Project.API.Data.Migrations
{
    [DbContext(typeof(WebshopDBContext))]
    partial class WebshopDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.BasketEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("ShippingPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Basket");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(9205),
                            IsActive = true,
                            ShippingPrice = 25.0,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(9209)
                        });
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.BasketProductEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BasketEntityID")
                        .HasColumnType("int");

                    b.Property<int>("BasketID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("SmartphoneEntityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BasketEntityID");

                    b.HasIndex("SmartphoneEntityID");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.BrandEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8491),
                            IsActive = true,
                            Name = "Samsung",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8497)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8504),
                            IsActive = true,
                            Name = "Apple",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8507)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8512),
                            IsActive = true,
                            Name = "Google",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8515)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8520),
                            IsActive = true,
                            Name = "Huawei",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8523)
                        },
                        new
                        {
                            ID = 5,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8527),
                            IsActive = true,
                            Name = "OnePlus",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8530)
                        });
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8117),
                            IsActive = true,
                            Name = "Smartphones",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8188)
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8209),
                            IsActive = true,
                            Name = "Accessories",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8212)
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8217),
                            IsActive = true,
                            Name = "Tablets",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            ID = 4,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8225),
                            IsActive = true,
                            Name = "Wearables",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8228)
                        });
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.OrderProductEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderEntityID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("SmartphoneEntityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OrderEntityID");

                    b.HasIndex("SmartphoneEntityID");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.SmartphoneEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MemoryCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("ScreenSize")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Smartphones");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Phantom Gray",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8616),
                            Description = "Latest Samsung smartphone with high-end specs.",
                            Image = "https://picsum.photos/181",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Samsung Galaxy S21",
                            Price = 799.99000000000001,
                            Stock = 25,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8621)
                        },
                        new
                        {
                            ID = 2,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Midnight",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8636),
                            Description = "New iPhone with advanced features.",
                            Image = "https://picsum.photos/182",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Apple iPhone 13",
                            Price = 999.99000000000001,
                            Stock = 30,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8639)
                        },
                        new
                        {
                            ID = 3,
                            BrandID = 3,
                            CategoryID = 1,
                            Colour = "Stormy Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8646),
                            Description = "Google's latest smartphone with clean Android experience.",
                            Image = "https://picsum.photos/183",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Google Pixel 6",
                            Price = 699.99000000000001,
                            Stock = 20,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8650)
                        },
                        new
                        {
                            ID = 4,
                            BrandID = 4,
                            CategoryID = 1,
                            Colour = "Golden Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8656),
                            Description = "High-end smartphone from Huawei.",
                            Image = "https://picsum.photos/184",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Huawei P50",
                            Price = 899.99000000000001,
                            Stock = 15,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8659)
                        },
                        new
                        {
                            ID = 5,
                            BrandID = 5,
                            CategoryID = 1,
                            Colour = "Winter Mist",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8666),
                            Description = "Flagship killer from OnePlus.",
                            Image = "https://picsum.photos/185",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "OnePlus 9",
                            Price = 729.99000000000001,
                            Stock = 18,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8669)
                        },
                        new
                        {
                            ID = 6,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Mystic Bronze",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8678),
                            Description = "Samsung's premium phone with S-Pen.",
                            Image = "https://picsum.photos/186",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Samsung Galaxy Note 20",
                            Price = 949.99000000000001,
                            Stock = 10,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8681)
                        },
                        new
                        {
                            ID = 7,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Blue",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8687),
                            Description = "Previous generation iPhone with great performance.",
                            Image = "https://picsum.photos/187",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Apple iPhone 12",
                            Price = 799.99000000000001,
                            Stock = 22,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8690)
                        },
                        new
                        {
                            ID = 8,
                            BrandID = 3,
                            CategoryID = 1,
                            Colour = "Just Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8697),
                            Description = "Compact and powerful Google phone.",
                            Image = "https://picsum.photos/188",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Google Pixel 5",
                            Price = 599.99000000000001,
                            Stock = 25,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8700)
                        },
                        new
                        {
                            ID = 9,
                            BrandID = 4,
                            CategoryID = 1,
                            Colour = "Space Silver",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8706),
                            Description = "Top-tier Huawei device with excellent camera.",
                            Image = "https://picsum.photos/189",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Huawei Mate 40",
                            Price = 1099.99,
                            Stock = 12,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8710)
                        },
                        new
                        {
                            ID = 10,
                            BrandID = 5,
                            CategoryID = 1,
                            Colour = "Aquamarine Green",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8718),
                            Description = "Fast and fluid experience from OnePlus.",
                            Image = "https://picsum.photos/190",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "OnePlus 8T",
                            Price = 649.99000000000001,
                            Stock = 17,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8721)
                        },
                        new
                        {
                            ID = 11,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Phantom Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8728),
                            Description = "Folding phone with a large display.",
                            Image = "https://picsum.photos/191",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Samsung Galaxy Z Fold 3",
                            Price = 1799.99,
                            Stock = 5,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8731)
                        },
                        new
                        {
                            ID = 12,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Red",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8738),
                            Description = "Compact iPhone with powerful internals.",
                            Image = "https://picsum.photos/192",
                            IsActive = true,
                            MemoryCapacity = 64,
                            Name = "Apple iPhone SE",
                            Price = 399.99000000000001,
                            Stock = 40,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8741)
                        },
                        new
                        {
                            ID = 13,
                            BrandID = 3,
                            CategoryID = 1,
                            Colour = "Barely Blue",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8749),
                            Description = "Affordable Google phone with great camera.",
                            Image = "https://picsum.photos/193",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Google Pixel 4a",
                            Price = 349.99000000000001,
                            Stock = 33,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8752)
                        },
                        new
                        {
                            ID = 14,
                            BrandID = 4,
                            CategoryID = 1,
                            Colour = "Midnight Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8758),
                            Description = "Budget-friendly Huawei device.",
                            Image = "https://picsum.photos/194",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Huawei Y9s",
                            Price = 249.99000000000001,
                            Stock = 19,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8761)
                        },
                        new
                        {
                            ID = 15,
                            BrandID = 5,
                            CategoryID = 1,
                            Colour = "Gray Onyx",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8768),
                            Description = "Mid-range OnePlus phone with great value.",
                            Image = "https://picsum.photos/195",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "OnePlus Nord",
                            Price = 399.99000000000001,
                            Stock = 24,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8771)
                        },
                        new
                        {
                            ID = 16,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Awesome Blue",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8777),
                            Description = "Solid mid-range Samsung device.",
                            Image = "https://picsum.photos/196",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Samsung Galaxy A52",
                            Price = 349.99000000000001,
                            Stock = 35,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8780)
                        },
                        new
                        {
                            ID = 17,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Green",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8786),
                            Description = "Previous generation iPhone with great performance.",
                            Image = "https://picsum.photos/197",
                            IsActive = true,
                            MemoryCapacity = 64,
                            Name = "Apple iPhone 11",
                            Price = 599.99000000000001,
                            Stock = 28,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8789)
                        },
                        new
                        {
                            ID = 18,
                            BrandID = 3,
                            CategoryID = 1,
                            Colour = "Not Pink",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8798),
                            Description = "Older Google phone with great features.",
                            Image = "https://picsum.photos/198",
                            IsActive = true,
                            MemoryCapacity = 64,
                            Name = "Google Pixel 3 XL",
                            Price = 499.99000000000001,
                            Stock = 14,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8801)
                        },
                        new
                        {
                            ID = 19,
                            BrandID = 4,
                            CategoryID = 1,
                            Colour = "Crush Green",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8808),
                            Description = "Stylish and affordable Huawei device.",
                            Image = "https://picsum.photos/199",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Huawei Nova 7i",
                            Price = 299.99000000000001,
                            Stock = 21,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8811)
                        },
                        new
                        {
                            ID = 20,
                            BrandID = 5,
                            CategoryID = 1,
                            Colour = "Nebula Blue",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8817),
                            Description = "Premium OnePlus device with pop-up camera.",
                            Image = "https://picsum.photos/200",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "OnePlus 7 Pro",
                            Price = 599.99000000000001,
                            Stock = 20,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8820)
                        },
                        new
                        {
                            ID = 21,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Cosmic Gray",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8827),
                            Description = "Flagship Samsung smartphone with advanced camera features.",
                            Image = "https://picsum.photos/201",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Samsung Galaxy S20",
                            Price = 999.99000000000001,
                            Stock = 15,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8830)
                        },
                        new
                        {
                            ID = 22,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8837),
                            Description = "Latest Apple iPhone with dual camera system.",
                            Image = "https://picsum.photos/202",
                            IsActive = true,
                            MemoryCapacity = 64,
                            Name = "Apple iPhone 11",
                            Price = 699.99000000000001,
                            Stock = 30,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8840)
                        },
                        new
                        {
                            ID = 23,
                            BrandID = 3,
                            CategoryID = 1,
                            Colour = "Just Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8846),
                            Description = "Google's smartphone with excellent camera and Google Assistant integration.",
                            Image = "https://picsum.photos/203",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Google Pixel 4",
                            Price = 799.99000000000001,
                            Stock = 25,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8850)
                        },
                        new
                        {
                            ID = 24,
                            BrandID = 4,
                            CategoryID = 1,
                            Colour = "Aurora",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8857),
                            Description = "High-end Huawei device with superior zoom camera capabilities.",
                            Image = "https://picsum.photos/204",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "Huawei P30 Pro",
                            Price = 899.99000000000001,
                            Stock = 10,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8860)
                        },
                        new
                        {
                            ID = 25,
                            BrandID = 2,
                            CategoryID = 1,
                            Colour = "Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8866),
                            Description = "New iphone flagship!",
                            Image = "https://picsum.photos/205",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Iphone 15 Pro Max",
                            Price = 949.99000000000001,
                            Stock = 12,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8870)
                        },
                        new
                        {
                            ID = 26,
                            BrandID = 1,
                            CategoryID = 1,
                            Colour = "Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8876),
                            Description = "New camera's, new design.",
                            Image = "https://picsum.photos/206",
                            IsActive = true,
                            MemoryCapacity = 128,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 499.99000000000001,
                            Stock = 50,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8879)
                        },
                        new
                        {
                            ID = 27,
                            BrandID = 5,
                            CategoryID = 1,
                            Colour = "Onyx Black",
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8888),
                            Description = "Next-gen OnePlus device with fluid display and wireless charging.",
                            Image = "https://picsum.photos/207",
                            IsActive = true,
                            MemoryCapacity = 256,
                            Name = "OnePlus 8 Pro",
                            Price = 799.99000000000001,
                            Stock = 18,
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(8891)
                        });
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BasketID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BasketID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketID = 1,
                            Created = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(9123),
                            Email = "test@test.be",
                            IsActive = true,
                            Name = "TestUser",
                            Password = "123",
                            Role = "[\"Admin\"]",
                            Updated = new DateTime(2024, 5, 31, 10, 10, 2, 694, DateTimeKind.Local).AddTicks(9130)
                        });
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.BasketProductEntity", b =>
                {
                    b.HasOne("Webshop_Project.API.Data.Entities.BasketEntity", null)
                        .WithMany("ListProducts")
                        .HasForeignKey("BasketEntityID");

                    b.HasOne("Webshop_Project.API.Data.Entities.SmartphoneEntity", null)
                        .WithMany("ProductsInBaskets")
                        .HasForeignKey("SmartphoneEntityID");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.OrderProductEntity", b =>
                {
                    b.HasOne("Webshop_Project.API.Data.Entities.OrderEntity", null)
                        .WithMany("ListProducts")
                        .HasForeignKey("OrderEntityID");

                    b.HasOne("Webshop_Project.API.Data.Entities.SmartphoneEntity", null)
                        .WithMany("ProductsInOrders")
                        .HasForeignKey("SmartphoneEntityID");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.SmartphoneEntity", b =>
                {
                    b.HasOne("Webshop_Project.API.Data.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop_Project.API.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Webshop_Project.API.Data.Entities.BasketEntity", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.BasketEntity", b =>
                {
                    b.Navigation("ListProducts");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.OrderEntity", b =>
                {
                    b.Navigation("ListProducts");
                });

            modelBuilder.Entity("Webshop_Project.API.Data.Entities.SmartphoneEntity", b =>
                {
                    b.Navigation("ProductsInBaskets");

                    b.Navigation("ProductsInOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
